"""add_security_question_to_users

Revision ID: a11f178480ec
Revises: cf7d019f0ebd
Create Date: 2026-07-02 18:29:36.752470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11f178480ec'
down_revision: Union[str, None] = 'cf7d019f0ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer_hash')
    op.drop_column('users', 'security_question')
    # ### end Alembic commands ###
